module.exports = exports = {
    fr: {
        login: {
            active: "Garder la session active",
            cancel: "Annuler",
            confirmed: "Confirmez votre mot de passe",
            connection: "Connexion",
            create: "Créer Compte",
            email: "exemple@mail.com",
            errConfirmed: "Les mots de passe ne sont pas identiques!",
            errName: "Le nom doit contenir au moins 4 caractères!",
            errPwd: "Le mot de passe doit contenir entre 4 et 12 caractères!",
            lang: "fr",
            name: "Nom",
            password: "Mot de passe",
            title: "Bibliotech Login",
            valid: "Valider"
        },
        bibliotech: {
            add: "Ajouter",
            addbook: "Ajouter un livre",
            affich: "Afficher le menu",
            affichMore: "Afficher la suite",
            all: "Tous",
            alls: "Toutes",
            author: "Auteur",
            authors: "Auteurs",
            categories: "Catégories",
            collection: "Bibliothèque",
            comments: "Commentaires",
            confirmPwd: "Confirmez mot de passe",
            contacts: "Contacts",
            deleteAccount: "Supprimer mon compte",
            description: "Description",
            disposition: "Enregistrer la disposition",
            english: "Anglais",
            errConfirm: "Les mots de passe ne sont pas identiques!",
            errFilter: "Le filtre doit contenir au moins 3 caractères!",
            errName: "Le nom doit contenir au moins 4 caractères!",
            errNotif: "Vous ne pouvez pas vous notifier!",
            errPwd: "Le mot de passe doit contenir entre 4 et 12 caractères!",
            errSearch: "La recherche doit contenir au moins 3 caractères!",
            filter: "Filtre",
            french: "Français",
            gconnexion: "Connexion Google",
            gexport: "Exporter maintenant",
            gimport: "Importer maintenant",
            gplus: "Google +",
            gsync: "Synchronisation automatique Google",
            isbn: "ISBN",
            language: "Langue",
            logout: "Déconnexion",
            mask: "Masquer le menu",
            modPwd: "Modifier mot de passe",
            msgPwd: "Mot de passe invalide!",
            name: "Nom",
            nbBooks: "Nombre de livres enregistrés",
            nbPages: "Nombre de pages",
            newPwd: "Nouveau mot de passe",
            newTag: "Nouveau tag",
            note: "Note",
            notifications: "Notifications",
            on: "le",
            password: "Mot de passe",
            profile: "Profil",
            publishBy: "Edité par",
            publisher: "Editeur",
            readersComments: "Avis des lecteurs",
            recommand4u: "Recommandés pour vous",
            remove: "Supprimer",
            search: "Recherche",
            searchby: "Rechercher par",
            sorts: "Tris",
            tags: "Tags",
            title: "Titre",
            valid: "Valider"
        }
    },
    en: {
        login: {
            lang: "en",
            title: "Bibliotech Login",
            email: "someone@mail.com",
            name: "Name",
            password: "Password",
            confirmed: "Confirm password",
            active: "Stay connected",
            create: "New Account",
            connection: "Connection",
            valid: "Valid",
            cancel: "Cancel",
            errName: "Name field must contain at least 4 characters!",
            errPwd: "Password field must contain between 4 and 12 characters!",
            errConfirmed: "Password fields are not identical!"
        },
        bibliotech: {
            add: "Add",
            addbook: "Add a book",
            affich: "Menu",
            affichMore: "display following",
            all: "All",
            alls: "All",
            author: "Author",
            authors: "Authors",
            categories: "Categories",
            collection: "Collection",
            comments: "Comments",
            confirmPwd: "Confirm password",
            contacts: "Contacts",
            deleteAccount: "Delete account",
            description: "Description",
            disposition: "Save disposition",
            english: "English",
            errConfirm: "Password fields are not identical!",
            errFilter: "Filter field must contain at least 3 characters!",
            errName: "Name field must contain at least 4 characters!",
            errNotif: "You can not notify you!",
            errPwd: "Password field must contain between 4 and 12 characters!",
            errSearch: "Search field must contain at least 3 characters!",
            filter: "Filter",
            french: "Français",
            gconnexion: "Google Connection",
            gexport: "Export now",
            gimport: "Import now",
            gplus: "Google +",
            gsync: "Auto sync Google",
            isbn: "ISBN",
            language: "Language",
            logout: "logout",
            mask: "Menu",
            modPwd: "Change password",
            msgPwd: "Invalid password!",
            name: "Name",
            nbBooks: "Books number",
            nbPages: "Pages number",
            newPwd: "New password",
            newTag: "New tag",
            note: "Note",
            notifications: "Notifications",
            on: "on",
            password: "Password",
            profile: "Profile",
            publishBy: "Publish by",
            publisher: "Publisher",
            readersComments: "Readers comments",
            recommand4u: "Recommand 4 u",
            remove: "Delete",
            search: "Search",
            searchby: "Search by",
            sorts: "Sorts",
            tags: "Tags",
            title: "Title",
            valid: "Ok"
        }
    }
};
