module.exports = exports = {
    fr: {
        login: {
            lang: "fr",
            active: "Garder la session active",
            cancel: "Annuler",
            confirmed: "Confirmez votre mot de passe",
            connection: "Connexion",
            create: "Créer Compte",
            email: "exemple@mail.com",
            errConfirmed: "Les mots de passe ne sont pas identiques!",
            errName: "Le nom doit contenir au moins 4 caractères!",
            errPwd: "Le mot de passe doit contenir entre 4 et 12 caractères!",
            forgetPassword: "Mot de passe oublié!",
            lang: "fr",
            name: "Nom",
            password: "Mot de passe",
            title: "Bibliotech Login",
            valid: "Valider"
        },
        bibliotech: {
            lang: "fr",
            add: "Ajouter",
            addbook: "Ajouter un livre",
            affich: "Afficher le menu",
            affichMore: "Afficher la suite",
            all: "Tous",
            alls: "Toutes",
            author: "Auteur",
            authors: "Auteurs",
            authorsWithComa: "Auteurs séparés par une virgule",
            cancel: "Annuler",
            categories: "Catégories",
            close: "Fermer",
            collection: "Bibliothèque",
            comments: "Commentaires",
            connex: "Recherche connexe",
            confirmPwd: "Confirmez mot de passe",
            contacts: "Contacts",
            deleteAccount: "Supprimer mon compte",
            deleteConfirm: "Cette opération est irréversible. Etes-vous de vouloir supprimer votre compte?",
            description: "Description",
            disposition: "Enregistrer la disposition",
            english: "Anglais",
            errConfirm: "Les mots de passe ne sont pas identiques!",
            errFilter: "Le filtre doit contenir au moins 3 caractères!",
            errName: "Le nom doit contenir au moins 4 caractères!",
            error: "Erreur",
            errPwd: "Le mot de passe doit contenir entre 4 et 12 caractères!",
            errRecommand: "Vous ne pouvez pas vous notifier!",
            errSearch: "La recherche doit contenir au moins 3 caractères!",
            errTitle: "Le titre doit contenir au moins 6 caractères!",
            filter: "Filtre",
            french: "Français",
            from: "Recommandé par",
            fullscreen: "Plein écran",
            gbooks: "Google books",
            gconnexion: "Connexion Google",
            gexport: "Exporter maintenant",
            gimport: "Importer maintenant",
            gplus: "Google +",
            gsync: "Synchronisation automatique Google",
            info: "Information",
            isbn: "ISBN",
            isbn10: "ISBN10",
            isbn13: "ISBN13",
            language: "Langue",
            logout: "Déconnexion",
            mask: "Masquer le menu",
            mNote: "Note moyenne",
            modify: "Modifier",
            modPwd: "Modifier mot de passe",
            msgPwd: "Mot de passe invalide!",
            name: "Nom",
            navigatorError: "Votre navigateur n'est pas compatible!!!",
            nbBooks: "Nombre de livres enregistrés",
            nbPages: "Nombre de pages",
            newBook: "Nouvel enregistrement",
            newPwd: "Nouveau mot de passe",
            newTag: "Nouvelle étiquette",
            next: "Suivant ❯",
            noConnect: "Connexion avec le serveur interrompu.",
            note: "Note",
            notifications: "Notifications",
            on: "le",
            password: "Mot de passe",
            preview: "Preview",
            previous: "❮ Précédent",
            profile: "Profil",
            publishBy: "Edité par",
            publishedDate: "Publié le",
            publisher: "Editeur",
            readersComments: "Avis des lecteurs",
            recommand: "Recommandé à un ami",
            recommand4u: "Recommandés pour vous",
            recommandLegend: "Si votre ami est inscrit, il recevra une notification de votre part.\nDans le cas contraire, il recevra par mail une invitation au site.",
            recommandMail: "Email",
            recommandName: "vous recommande",
            recommandSend: "Envoyer",
            remove: "Supprimer",
            save: "Enregistrer",
            search: "Recherche",
            searchby: "Rechercher par",
            searchGo: "Lancer",
            sorts: "Tris",
            subtitle: "Subtitle",
            tags: "Etiquettes",
            title: "Titre",
            torecommand: "Recommander",
            upload: "Télécharger une couverture",
            valid: "Valider",
            warning: "Attention",
            waiting: "Veuillez patienter...",
            welcome: "Bienvenu sur Biblio.tech!"
        }
    },
    en: {
        login: {
            lang: "en",
            title: "Bibliotech Login",
            email: "someone@mail.com",
            name: "Name",
            password: "Password",
            confirmed: "Confirm password",
            active: "Stay connected",
            create: "New Account",
            connection: "Connection",
            valid: "Valid",
            cancel: "Cancel",
            errName: "Name field must contain at least 4 characters!",
            errPwd: "Password field must contain between 4 and 12 characters!",
            errConfirmed: "Password fields are not identical!",
            forgetPassword: "Forget Password"
        },
        bibliotech: {
            lang: "en",
            add: "Add",
            addbook: "Add a book",
            affich: "Menu",
            affichMore: "display following",
            all: "All",
            alls: "All",
            author: "Author",
            authors: "Authors",
            authorsWithComa: "Authors separated by commas",
            cancel: "Cancel",
            categories: "Categories",
            close: "Close",
            collection: "Collection",
            comments: "Comments",
            confirmPwd: "Confirm password",
            connex: "Connex search",
            contacts: "Contacts",
            deleteAccount: "Delete account",
            deleteConfirm: "This is irreversible. Do you want to delete your account?",
            description: "Description",
            disposition: "Save disposition",
            english: "English",
            errConfirm: "Password fields are not identical!",
            errFilter: "Filter field must contain at least 3 characters!",
            errName: "Name field must contain at least 4 characters!",
            error: "Error",
            errPwd: "Password field must contain between 4 and 12 characters!",
            errRecommand: "You can not notify you!",
            errSearch: "Search field must contain at least 3 characters!",
            errTitle: "Title field must contain at least 6 characters!",
            filter: "Filter",
            french: "Français",
            from: "Recommanded by",
            fullscreen: "Fullscreen",
            gconnexion: "Google Connection",
            gexport: "Export now",
            gimport: "Import now",
            gbooks: "Google books",
            gplus: "Google +",
            gsync: "Auto sync Google",
            info: "Information",
            isbn: "ISBN",
            isbn10: "ISBN10",
            isbn13: "ISBN13",
            language: "Language",
            logout: "logout",
            mask: "Menu",
            modify: "Change",
            modPwd: "Change password",
            mNote: "Average rating",
            msgPwd: "Invalid password!",
            name: "Name",
            navigatorError: "Your browser is not compatible!!!",
            nbBooks: "Books number",
            nbPages: "Pages number",
            newBook: "New record",
            newPwd: "New password",
            newTag: "New tag",
            next: "Next ❯",
            noConnect: "No connection.",
            note: "Note",
            notifications: "Notifications",
            on: "on",
            password: "Password",
            preview: "Preview",
            previous: "❮ Previous",
            profile: "Profile",
            publishBy: "Publish by",
            publishedDate: "Published on",
            publisher: "Publisher",
            readersComments: "Readers comments",
            recommand: "Recommand to a friend",
            recommand4u: "Recommand 4 u",
            recommandLegend: "If your friend is registered , he will receive a notification on your part. Otherwise , he will receive by email an invitation to the site.",
            recommandMail: "Friend's email",
            recommandName: "recommand to you",
            recommandSend: "Send",
            remove: "Delete",
            save: "Save",
            search: "Search",
            searchby: "Search by",
            searchGo: "Go",
            sorts: "Sort",
            subtitle: "Subtitle",
            tags: "Tags",
            title: "Title",
            torecommand: "To recomand",
            upload: "Upload a cover",
            valid: "Ok",
            warning: "Warning",
            waiting: "Please wait...",
            welcome: "Welcome to Biblio.tech!"
        }
    }
};
